### ISSUE TITLE
Incorrect 'via' should raise more helpful error.

### ISSUE THREAD

**Issue by MarkMurphy** [balderdashy/waterline-schema#17]
I have two models (many-to-many):

**User.js**
```javascript
var User = {
  ...
  attributes: {
   projects: {
      collection: 'Project',
      via: 'user' // Notice that this should be 'users' not 'user'
    }
  },
 ...
}

module.exports = User;
```

**Project.js**
```javascript
// models/project.js
var Project = {
  ...
  attributes: {
   users: {
      collection: 'User',
      via: 'projects'
    }
  },
 ...
}

module.exports = Project;
```

```shell
$ sails lift

info: Starting app...


/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:46
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at exports.object.hasOwnProperty (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/utils.js:46:14)
    at JoinTables.parseAttribute (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:145:26)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:80:22
    at Array.forEach (native)
    at JoinTables.buildJoins (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:79:24)
    at new JoinTables (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema/joinTables.js:40:23)
    at new module.exports (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/waterline-schema/lib/waterline-schema.js:33:17)
    at Waterline.initialize (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:106:17)
    at buildORM (/usr/local/lib/node_modules/sails/lib/hooks/orm/build-orm.js:48:15)
```

I would expect this to provide me with an error message telling me that Project does not reference an attribute key 'user' while attempting to map User.attributes.projects via Project.attributes.user, or something along those lines.

**Comment by airtonix** [comment]
Just manually pasted the commit 475a8b0 into the my current install of `waterline-schema`, and it now gives a useful error message. I think this will save a lot of time for tired, wary or newcomers to sailsjs.

**Comment by MarkMurphy** [comment]
That's awesome! Thanks @yagoferrer, how about submitting that as a pull-request?

**Comment by yagoferrer** [comment]
@MarkMurphy I sent that as PR 28d ago.

https://github.com/balderdashy/waterline-schema/pull/18
